'use client'

interface PdfLine {
  label: string
  value: string
}

interface PdfDownloadButtonProps {
  title: string
  amount: string
  subtitle: string
  lines: PdfLine[]
  filename?: string
}

function pdfEscape(value: string) {
  return value
    .replace(/[–—]/g, '-')
    .replace(/[×]/g, 'x')
    .replace(/[÷]/g, '/')
    .replace(/[^\x20-\x7E]/g, '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function buildPdf({ title, amount, subtitle, lines }: Omit<PdfDownloadButtonProps, 'filename'>) {
  const now = new Date().toLocaleDateString('en-AE', { day: 'numeric', month: 'short', year: 'numeric' })
  const contentLines = [
    { size: 18, y: 760, text: title },
    { size: 28, y: 720, text: amount },
    { size: 12, y: 696, text: subtitle },
    { size: 10, y: 668, text: `Generated by UAE Gratuity Check on ${now}` },
    ...lines.map((line, index) => ({
      size: 12,
      y: 626 - index * 24,
      text: `${line.label}: ${line.value}`,
    })),
    { size: 9, y: 86, text: 'Estimate only. Confirm your final settlement with your employer, MOHRE, or a legal adviser.' },
    { size: 9, y: 70, text: 'https://www.uaegratuitycheck.com' },
  ]

  const stream = [
    'BT',
    '/F1 10 Tf',
    ...contentLines.flatMap((line) => [
      `/F1 ${line.size} Tf`,
      `72 ${line.y} Td (${pdfEscape(line.text)}) Tj`,
      `-72 -${line.y} Td`,
    ]),
    'ET',
  ].join('\n')

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ]

  let body = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((object, index) => {
    offsets.push(body.length)
    body += `${index + 1} 0 obj\n${object}\nendobj\n`
  })
  const xrefOffset = body.length
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  offsets.slice(1).forEach((offset) => {
    body += `${String(offset).padStart(10, '0')} 00000 n \n`
  })
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`
  return body
}

export default function PdfDownloadButton({
  title,
  amount,
  subtitle,
  lines,
  filename = 'uae-gratuity-calculation.pdf',
}: PdfDownloadButtonProps) {
  function downloadPdf() {
    const pdf = buildPdf({ title, amount, subtitle, lines })
    const blob = new Blob([pdf], { type: 'application/pdf' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = filename
    document.body.appendChild(anchor)
    anchor.click()
    anchor.remove()
    URL.revokeObjectURL(url)
  }

  return (
    <button type="button" className="pdf-download-btn" onClick={downloadPdf}>
      Download PDF result
    </button>
  )
}
