// Visible FAQ + FAQPage JSON-LD for the domestic worker pages (EN and AR).
export const domesticFaqsEn = [
  { q: 'Are domestic workers entitled to gratuity in the UAE?', a: 'The current law, Federal Decree-Law No. 9 of 2022, has an article titled End-of-Service Gratuity (Article 22), but it only says the Cabinet may approve the rules for calculating and paying it. No Cabinet decision setting a formula had been published when we checked on 4 October 2026, and the executive regulation (Cabinet Resolution No. 106 of 2022) does not set one. In practice the amount depends on the MOHRE-approved contract; MOHRE’s Domestic Workers Dues Calculator gives the official figure.' },
  { q: 'Is there gratuity for housemaids in the UAE in 2026?', a: 'Housemaids, nannies, drivers and cooks hired by a household are domestic workers under Federal Decree-Law No. 9 of 2022, so the answer above applies. A cleaner employed by a cleaning company is usually a private-sector employee under the Labour Law and gets the standard 21/30-day gratuity.' },
  { q: 'Is there a MOHRE domestic worker gratuity calculator?', a: 'Yes. MOHRE lists a Domestic Workers Dues Calculator in its services directory (helpline 600590000). Use it for the official figure; our estimator only applies the rate you choose.' },
  { q: 'Is the 14 days per year rule still valid?', a: 'Not as law. 14 days of basic wage per year is the rate commonly attributed to Federal Law No. 10 of 2017, which Article 31 of Federal Decree-Law No. 9 of 2022 repealed from 15 December 2022. You can still use 14 days in our estimator as a reference, or the rate written in your contract.' },
  { q: 'How soon must a domestic worker’s final dues be paid?', a: 'Article 19(2) of Federal Decree-Law No. 9 of 2022 requires the employer to pay all of the worker’s financial entitlements within 10 days of the employment agreement ending.' },
  { q: 'What happens to unused annual leave?', a: 'If the agreement ends before the worker takes their leave, they are entitled to cash for the leave days due, calculated on their last wage (Article 10(5)).' },
  { q: 'How long does a domestic worker have to make a claim?', a: 'Lawsuits for rights under the Decree-Law cannot be heard more than 3 months after the work relationship ends (Article 26(2)). Workers are exempt from court fees, and MOHRE can decide disputes worth up to AED 50,000 itself (Article 23).' },
]

export const domesticFaqsAr = [
  { q: 'هل تستحق العمالة المساعدة مكافأة نهاية الخدمة في الإمارات؟', a: 'يتضمن المرسوم بقانون اتحادي رقم 9 لسنة 2022 مادة بعنوان مكافأة نهاية الخدمة (المادة 22)، لكنها تنص فقط على أن مجلس الوزراء يصدر أنظمة وآليات احتسابها وسدادها. ولم يُنشر قرار بهذه القواعد حتى تاريخ مراجعتنا في 4 أكتوبر 2026، كما أن اللائحة التنفيذية (قرار مجلس الوزراء رقم 106 لسنة 2022) لا تحدد معادلة. لذلك يعتمد المبلغ عملياً على العقد المعتمد من الوزارة، وتعطي خدمة احتساب المستحقات للعمالة المساعدة الرقم الرسمي.' },
  { q: 'هل قاعدة 14 يوماً عن كل سنة ما زالت سارية؟', a: 'ليس كنص قانوني. نسبة 14 يوماً من الأجر الأساسي عن كل سنة تُنسب إلى القانون الاتحادي رقم 10 لسنة 2017 الذي ألغته المادة 31 من المرسوم بقانون رقم 9 لسنة 2022 اعتباراً من 15 ديسمبر 2022. يمكن استخدامها في الحاسبة للاسترشاد فقط أو استخدام النسبة المذكورة في العقد.' },
  { q: 'متى يجب دفع مستحقات العامل المساعد؟', a: 'تلزم المادة 19 صاحب العمل بدفع جميع المستحقات المالية للعامل خلال 10 أيام من تاريخ انتهاء عقد العمل.' },
  { q: 'ماذا عن الإجازة السنوية غير المستخدمة؟', a: 'إذا انتهى العقد قبل حصول العامل على إجازته، يستحق تعويضاً نقدياً عن أيام الإجازة المستحقة يُحسب على آخر أجر تقاضاه (المادة 10).' },
  { q: 'ما المدة المتاحة لتقديم مطالبة؟', a: 'لا تُسمع الدعوى بأي حق ناشئ عن المرسوم بقانون بعد مرور 3 أشهر من انتهاء علاقة العمل (المادة 26)، والعمال معفون من الرسوم القضائية، وتفصل الوزارة في النزاعات التي لا تتجاوز قيمتها 50,000 درهم (المادة 23).' },
]
